### ISSUE TITLE
mismatch of htuSamplerGetLatest() parameters between header/code

### ISSUE THREAD

**Issue by tcj** [bristlemouth/bm_protocol#34]
htuSampler.cpp --

`bool htuSamplerGetLatest(float &temperature, float &humidity) {`

htuSampler.h

`bool htuSamplerGetLatest(float &humidity, float &temperature);`

**Comment by tcj** [comment]
perhaps because the sensor is called htuXYZ everywhere, the header file should win and humidity should be first

**Comment by tcj** [comment]
note this also affects the code in src/apps/bm_devkit/devkit_monitor

https://github.com/bristlemouth/bm_protocol/blob/5a02a590572687c65da68a23b581dc542bb2e748/src/apps/bm_devkit/devkit_monitor/user_code/user_code.cpp#L186

**Comment by tcj** [comment]
has this been fixed/addressed?

https://www.notion.so/bristlemouth/Bristlemouth-Dev-Kit-Guide-5-Developing-a-Simple-Application-44333bff94b346cc8eb1d512b8cf0824?pvs=4#1bc62a32dc9f46cca23c2f98b2cfdfb2

https://sofarocean.slack.com/archives/C027PLD7L2F/p1720477485812319

**Comment by victorsowa12** [comment]
done! https://github.com/bristlemouth/bm_protocol/pull/149#pullrequestreview-2164562769
